# Generated by Django 6.0.1 on 2026-01-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='society_landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
