# Generated by Django 6.0.1 on 2026-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
