# Generated by Django 6.0.1 on 2026-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishu',
            name='age',
            field=models.IntegerField(),
        ),
    ]
