# Generated by Django 6.0.1 on 2026-02-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_alter_ishu_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-22'),
            preserve_default=False,
        ),
    ]
