# Generated by Django 6.0.1 on 2026-02-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_ishu_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ishu',
        ),
    ]
